export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN = "LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CHECK_FOR_USER = "CHECK_FOR_USER";
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";

export const SEARCH_ROASTERS = "SEARCH_ROASTERS";
export const LOAD_ROASTERS = "LOAD_ROASTERS";
export const LOAD_ROASTER = "LOAD_ROASTER";

export const CREATE_ROAST = "CREATE_ROAST";
export const LOAD_ROAST = "LOAD_ROAST";
export const CREATE_ROAST_REVIEW = "CREATE_ROAST_REVIEW";
export const LOAD_ROASTS = "LOAD_ROASTS";

export const CREATE_FRIEND_REQUEST = "CREATE_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
export const LOAD_FRIEND_REQUESTS = "LOAD_FRIEND_REQUESTS";