export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN = "LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CHECK_FOR_USER = "CHECK_FOR_USER";

export const SEARCH_ROASTERS = "SEARCH_ROASTERS";
export const LOAD_ROASTERS = "LOAD_ROASTERS";
export const LOAD_ROASTER = "LOAD_ROASTER";

export const CREATE_ROAST = "CREATE_ROAST";
export const LOAD_ROAST = "LOAD_ROAST";
export const CREATE_ROAST_REVIEW = "CREATE_ROAST_REVIEW";